pyiron/project.py

Adding the new feature based on Joerg's suggestion

pyiron.project: Adding new feature create_atoms()

---

pyiron/project.py

Debugging the create_atoms() function

pyiron.project: Quick debug in create_atoms()

---

pyiron/base/objects/job/interactive.py

@samwaseda Can you check if that is the behaviour you expect?

Get prev structure

---

pyiron/lammps/control.py

Old string formatting had fix nph aniso reading temperature variables instead of pressure variablse

Get nph aniso to read pressure during langevin

---

pyiron/vasp/structure.py

No more unnecessary blank spaces. A minor cleanup.

vasp/structure.py: Cleaner write_poscar

---

pyiron/atomistics/job/atomistic.py
pyiron/atomistics/job/interactive.py
pyiron/base/job/interactive.py

@jan-janssen Can you see if the changes are okay?

spins added to the final structure

---

pyiron/vasp/outcar.py
tests/vasp/test_outcar.py

Improving the kinetic energy error parsing in VASP

Debug kin energy

---

pyiron/lammps/base.py
pyiron/vasp/base.py

Convergence criterion changed as mentioned here: https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/70

Convergence criterion

---

pyiron/base/server/queuestatus.py

raise valueError when maximum number of iterations is reached.

Wait for job - Bug Fix

---

pyiron/base/generic/parameters.py
pyiron/vasp/base.py

Commits to clean up the Vasp class

Cleanup vasp

---

pyiron/atomistics/job/atomistic.py
pyiron/lammps/base.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py

I also created `job.input.control.set_velocity`

Langevin velocity corrected

---

pyiron/lammps/base.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py

implement potentials_view() and potentials_list()

Lammps calc_md use default parameters

---

pyiron/atomistics/structure/sparse_list.py
tests/atomistics/structure/test_atoms.py

Repeat function with tags need to work well

Debug repeat

---

pyiron/vasp/outcar.py
tests/static/vasp_test_files/outcar_samples/OUTCAR_8
tests/vasp/test_outcar.py

Using regex for stable parsing

Debug outcar

---

pyiron/lammps/control.py

Fixing a bug where forced application of the old `delta_press` didn't work.
Also added rescaling of pressure units to accommodate non-metal Lammps units, and some minor documentation/beautification.

Md backwards compatibility

---

pyiron/atomistics/structure/atoms.py

The old one doesn't play well with PBC. Just use Ovito's which is working fine.

Deprecate broken voronoi

---

pyiron/vasp/vasprun.py
tests/static/vasp_test_files/vasprun_samples/vasprun_line.xml
tests/vasp/test_vasprun.py

Line mode generated kpoints list can now be parsed

Debug vasprun

---

pyiron/base/job/generic.py
pyiron/base/job/wrapper.py
pyiron/base/job/wrappercmd.py

Call non modal jobs directly from the command line

---

pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/sparse_list.py
pyiron/base/database/jobtable.py

This is cleaner and more complete

Use `numpy.integer` to represent all numpy integer types

---

.travis.yml
pyiron/atomistics/structure/atoms.py

get_distances implemented

---

pyiron/atomistics/structure/atoms.py

Maybe I'm going to talk about this function tomorrow at the pyiron meeting

Group by symmetry

---

pyiron/base/job/interactive.py

I wanted to put it in `validate_ready_to_run`, but I didn't manage it...

Validate lammps

---

pyiron/base/job/generic.py

Fix https://github.com/pyiron/pyiron/issues/224

Fix run_mode manual

---

pyiron/atomistics/job/atomistic.py
pyiron/dft/job/generic.py
pyiron/project.py

Option to wrap atoms before returning them!

Wrap atoms

---

pyiron/base/job/executable.py

for consistency with list_potentials() and list_queues()

implement list_executables()

---

docs/index.rst

20th June 2019: pyiron was downloaded over 5000 times on conda-forge https://anaconda.org/conda-forge/pyiron/ and 70% of our code are covered with unit tests https://coveralls.io/github/pyiron/pyiron?branch=master.

Announcement

---

pyiron/atomistics/job/atomistic.py
pyiron/atomistics/structure/atoms.py
pyiron/lammps/interactive.py

values changed for e_tol and f_tol from interactive 

---

pyiron/atomistics/job/atomistic.py

Discussion that I had initiated in gitlab. This of course considers the periodic boundary conditions as well.

Output displacement

---

pyiron/base/job/generic.py
pyiron/base/job/script.py
pyiron/base/master/list.py
pyiron/base/master/serial.py
pyiron/testing/randomatomistic.py

Fix read input

---

pyiron/base/generic/hdfio.py
pyiron/lammps/base.py

Please do not merge this yet - I still have to push the changes to h5io

New h5io interface

---

pyiron/base/job/executable.py

Now 'default' string is added to default names by Jan, and default version is recognized by it.

Default versions sorting

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Dont delete items in a for loop! (Apologies for ancient code)

Debug `__setitem_`

---

pyiron/atomistics/job/interactive.py

The number of atoms can not change - therefore the old implementation was ambitious

Performance improvement for Interactive jobs 

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

volume added as an attribute

---

pyiron/atomistics/structure/atoms.py
pyiron/lammps/potential.py
tests/atomistics/structure/test_atoms.py

Number of atoms of the majority species was wrong. And there was no DocString

Get majority species

---

pyiron/atomistics/job/atomistic.py

In order to animate the trajectories!

Remove requirement that the job has to be finished!

---

pyiron/vasp/base.py

RWIGS is possible to set and get as a dictionary. LAMBDA and RWIGS are mandatory to set in `set_spin_constraint`.

Improve spin cons

---

pyiron/base/generic/hdfio.py

bugfix for new path name in rewrite_hdf5

---

pyiron/atomistics/job/atomistic.py
tests/lammps/test_base.py

Option to overwrite trajectory positions!

Write traj

---

pyiron/vasp/base.py

EDDRMM warings will be written in pyiron.log. For jobs without 'eddrmm_handling' written in hdf5 file, default status is 'ignored'.

Improved EDDRMM warning handling

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Necessary for clusters and 2D structures

Allow for singular matrices to be set as cell value

---

pyiron/atomistics/structure/atoms.py

Now a simple 3d-vector can also be used.

small change in get_distances

---

pyiron/lammps/interactive.py

Now parameter-based potentials can be also used.

potential class corrected to include custom potential

---

pyiron/atomistics/job/atomistic.py

https://github.com/pyiron/pyiron/commit/af2ea35844c15c528dda452192610d294c0ee2e3

Fix output.indices for not interactive jobs

---

pyiron/base/settings/generic.py
tests/base/settings/test_generic_test_config.py

@SanderBorgmans Can you check if this resolves your issue with symbolic links?

Disable resolving symbolic links

---

pyiron/lammps/control.py

https://github.com/pyiron/pyiron/issues/434

Langevin fix

---

pyiron/base/generic/parameters.py
pyiron/lammps/base.py
pyiron/lammps/structure.py

Defining a generalized way of drawing bonds in LAMMPS through pyiron

Lammps bonds

---

pyiron/base/generic/parameters.py
pyiron/lammps/structure.py

Fixing some errors noticed during the simulation of ions in water

Fix lammps water

---

.ci_support/azure-unix-test-template.yml
.ci_support/setup_pyiron.sh
appveyor.yml
pyiron/base/project/generic.py
setup.py

As discussed with @jan-janssen [on the private gitlab board](https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/229)

Add an easy function for checking the git hash of each pyiron module

---

pyiron/base/project/generic.py

Static methods need no self argument

---

pyiron/vasp/base.py

according to https://www.vasp.at/wiki/wiki/index.php/ISYM

Set isym for VASP MD

---

pyiron/vasp/base.py
tests/vasp/test_vasp.py

Default: ENCUT	= largest ENMAX on the POTCAR file
https://www.vasp.at/wiki/index.php/ENCUT

Remove EnCUT

---

pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/ovito.py

Just a partial docstring for structure.analyse_ovito_cna_adaptive.
It's not complete because I don't know what all the output formats are/do, but it's not wrong. I'm really tired of having to open the source code each time I want to know what the allowable `mode`s are!
This is purely docstring editing, so I'm just going to merge it without waiting for any tests or reviews, but I wanted a more evident paper trail of my crime than a single commit to master ;)

Very basic docstring for CNA

---

pyiron/vasp/vasprun.py
tests/vasp/test_vasprun.py

A minor fix in order to parse element types

Fix vasprun

---

pyiron/base/generic/parameters.py
pyiron/lammps/base.py
pyiron/lammps/control.py
tests/lammps/test_base.py

Now average values can be calculated via:
```
lmp.input.control.measure_mean_value('energy_pot')
lmp.input.control.measure_mean_value('energy_tot')
lmp.input.control.measure_mean_value('volume')
lmp.input.control.measure_mean_value('temperature')
lmp.input.control.measure_mean_value('pressures')
```
And these values are stored in `lmp['output/generic']` with the prefix `mean_`

Lmp thermo average

---

pyiron/lammps/control.py
tests/lammps/test_control.py
tests/lammps/test_interactive.py

Now the average of anything can be calculated. For example, if user wants to calculate potential energy square, it suffices to write: `job.input.control.measure_mean_value('pe^2', 10, name='energy_pot_sq')`, where `name` is what is going to be stored in the hdf5 file (preceded by `mean_`).

Lmp average

---

pyiron/atomistics/md_analysis/water_analysis.py

Water analysis

---

docs/index.rst

WORKSHOP 
"WORKFLOWS FOR ATOMISTIC SIMULATION"
SCOPE 
It is increasingly common that atomistic simulations such as molecular 
dynamics or structural relaxation are used as engines that drive more 
complex simulation tasks, for example, the computation of phase diagrams 
or the search for novel materials with specific properties, etc. 
The workflow along the simulation chain then becomes an integral part of 
research and for transparent and reproducible results or for 
transferring to other materials systems it is essential that the 
workflow along the simulation chain is well documented. 
At this workshop leading international researchers will give an 
introduction to simulations and workflows that they use in their 
research. In the afternoons hands-on tutorials using pyiron will 
enable …

Announcement of the first pyiron Workshop - http://potentials.rub.de

---

pyiron/lammps/base.py
pyiron/lammps/control.py

This function calculates the potential energy of a particular atom in a given structure.

Pot per atom sam

---

pyiron/vasp/base.py

Sorting some issues while importing jobs with weird POSCAR ordering

Debug vasp import

---

pyiron/vasp/base.py

Added 'Gamma centered' k-points symmetrization scheme.

VASP Gamma mode implementation

---

pyiron/sphinx/base.py
tests/sphinx/test_base.py

bugfix set_empty_states

---

pyiron/sphinx/base.py

now band structure calculations are possible.

updated restart functions for BS calculations

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Apply a strain with a single number / 3-dim vector / epsilon matrix.
With `return_box` only the returned box will be strained

Apply strain

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Returns positions in spherical coordinates

Spherical coordiantes

---

.gitpod
README.rst

[![Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/pyiron/pyiron)

Add a simple gitpod config

---

pyiron/atomistics/job/atomistic.py
pyiron/atomistics/structure/atoms.py
pyiron/lammps/base.py
pyiron/lammps/interactive.py
pyiron/vasp/base.py
pyiron/vasp/vasprun.py
tests/atomistics/structure/test_atoms.py

Following last week's discussion

property setter for cell removed

---

pyiron/sphinx/base.py

decompress removed when restart is done

---

pyiron/atomistics/structure/atoms.py

updated to give all shell matrices

shell_matrix updated

---

pyiron/gaussian/gaussian.py

1) Restart functionality is still missing
2) Visualizing molecular orbitals is not implemented in a general way. This would require a separate 
cubegen job.

Gaussian module changes from ugent, with generic calc functions

---

pyiron/base/job/jobstatus.py
pyiron/vasp/base.py
tests/vasp/test_vasp.py

Add a new status 'warning' to jobs, and use it when Vasp faces EDDRMM issues.

Warning status

---

pyiron/atomistics/nma/nma.py

Revert "Remove nma module from the merge"

---

pyiron/atomistics/structure/atoms.py

minor change (no review required)

tolerance added to get_shell_matrix

---

pyiron/dft/job/generic.py
pyiron/sphinx/base.py
pyiron/vasp/base.py

new function for creating restart job for band structure calculations.

restart function for band structures

---

notebooks/bandstructure.ipynb
pyiron/sphinx/base.py

https://github.com/pyiron/pyiron/issues/580

Check if iron potential is available

---

pyiron/lammps/interactive.py

@raynol-dsouza This should fix your issue

Fix compatibility to pylammpsmpi

---

pyiron/atomistics/structure/atoms.py

Closes https://github.com/pyiron/pyiron/issues/606

Add ASE write function

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Fixes the issues mentioned here: https://github.com/pyiron/pyiron/issues/594

Non periodic

---

.ci_support/azure-unix-test-template.yml
.ci_support/environment.yml
.ci_support/setup_miniconda.sh
.ci_support/setup_pyiron.sh
appveyor.yml

Based on the discussion with @ashtonmv

Update continuous integration environment 

---

pyiron/table/datamining.py
pyiron/table/funct.py
tests/table/test_datamining.py

A new feature to filter the data using the project table itself rather than the job
```
pt_obj = PyironTable(pr)
pt_obj.db_filter_function = db_filter_function
pt_obj.filter_function = filter_function
pt_obj.add.get_incar
pt_obj.convert_to_object = False
pt_obj.create_table()
```

Pyiron tables

---

.ci_support/environment.yml
pyiron/thermodynamics/interfacemethod.py
setup.py

The interface method @lfzhu-phys and I developed.

Add interface method

---

notebooks/test_pyiron_installation.ipynb

https://mybinder.org/v2/gh/pyiron/pyiron/master?filepath=notebooks%2Ftest_pyiron_installation.ipynb

Add notebook to test pyiron installation 

---

pyiron/sphinx/base.py

Reflecting [this issue](https://github.com/pyiron/pyiron/issues/605)

order of parsing changed

---

.github/stale.yml

https://github.com/probot/stale 
Based on https://github.com/pyiron/pyiron/issues/639

Add stale bot 

---

pyiron/atomistics/master/phonopy.py

phonopy updated to circumvent all deprecation warnings

---

pyiron/sphinx/base.py

Mentioned in [this pull request](https://github.com/pyiron/pyiron/issues/653)

Plane wave cutoff

---

pyiron/vasp/base.py

Sorting the positions and forces when parsing from the OUTCAR file

Bug in VASP parsing from OUTCAR

---

pyiron/atomistics/structure/atoms.py

Visualization of magnetic moments in plot3d()

---

pyiron/lammps/base.py
pyiron/lammps/control.py

closes https://github.com/pyiron/pyiron/issues/665

Fix error message when calc_* is set before structure

---

pyiron/base/job/generic.py

Following the discussion https://github.com/pyiron/pyiron/issues/672

Simplify Python only jobs

---

pyiron/base/job/jobtype.py
pyiron/vasp/vaspsol.py

just a wrapper class to create separate executables

Add Vaspsol support

---

.travis.yml
binder/postBuild

Preparation for https://github.com/pyiron/pyiron-resources/pull/16

Mybinder: update postBuild

---

.travis.yml
binder/postBuild

* Update postBuild
* Update postBuild
* Update .travis.yml
* Update .travis.yml

Mybinder: update postBuild (#689)

---

docs/index.rst
docs/source/software.rst

Preview is available here: https://pyiron.readthedocs.io/en/software/source/software.html (it takes roughly 10 minutes for the preview to refresh after making changes on Github).

Add software partners

---

notebooks/tests_sphinx_sphinx_check_all.ipynb

As discussed in https://github.com/pyiron/pyiron/pull/709

Add Sam's Sphinx test notebook to integration tests 

---

notebooks/tests_sphinx_sphinx_check_all.ipynb

* Add files via upload
* Disable queue test

Add Sam's Sphinx test notebook to integration tests  (#710)

---

notebooks/tests_sphinx_sphinx_check_all.ipynb
pyiron/sphinx/interactive.py

forces missing in the list of interactive output tags

---

CONTRIBUTING.rst

'My job does not run on the queue' added as part of Debugging, as discussed in the pyiron meeting on 5.6.20.

:pencil: Add Debugging

---

pyiron/base/job/script.py

for publishing simulation protocols

Scriptjobs support input.json files

---

pyiron/base/job/generic.py
pyiron/base/job/jobstatus.py

job status bugfix

---

pyiron/__init__.py
pyiron/base/job/external.py
pyiron/base/job/script.py
pyiron/base/project/generic.py

Access input of a scriptjob by:
```
from pyiron import ExternalInput
input_dict = ExternalInput()
```
this is the same as:
```
from pyiron import Notebook
input_dict = Notebook().get_custom_dict()
```
Besides the scriptjob input also JSON files as input are supported, just place a JSON file named "input.json" next to the notebook.

External input

---

pyiron/atomistics/job/interactive.py
pyiron/interactive/sxextoptint.py

Please add:
```
super().__init__()
```
to existing classes.

Add logger to interactive interface

---

pyiron/vasp/base.py
tests/vasp/test_vasp.py

Will close the attached issue.

VASP: updating write magmoms

---

pyiron/vasp/base.py
tests/vasp/test_vasp.py

just a little bit updated + added some tests

Update spin constraints

---

docs/source/faq.rst

Added a short explanation on how to use a custom LAMMPS potential in pyiron in the docs/source/faq.rst

Update faq how to use a custom potential in LAMMPS

---

pyiron/base/job/generic.py

As discussed in the last meeting

Update runtime when calculations crashes

---

docs/source/faq.rst

Added a short explanation on how to use a custom LAMMPS potential in pyiron

Update how to use a custom potential in LAMMPS (#745)

---

notebooks/tests_sphinx_sphinx_check_all.ipynb

Fix for https://github.com/pyiron/pyiron/pull/750 
Two remarks: 
* Do not merge a pull request if a test fails. 
* The for the documentation it is essential that the notebooks in the notebooks folder include the output.

Fix updated Sphinx Notebook

---

pyiron/vasp/base.py

To fix importing VASP jobs (@samwaseda , can you try importing with this branch!?)

Fix vasp import

---

notebooks/tests_sphinx_sphinx_check_all.ipynb
pyiron/sphinx/base.py

Fix second part of [this issue](https://github.com/pyiron/pyiron/issues/769)

_spin_enabled changed to property

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Returns all symmetry-equivalent points of a given point.
```
structure.get_equivalent_points([0, 0, 0.5])
```
I guess this is what Jörg was suggesting (not sure).

Get equivalent points

---

pyiron/atomistics/structure/atoms.py

I'm not even sure if anyone has ever used this function, but I don't think it was working correctly and without DocString it's not even clear what's the difference between this one and `get_symmetry()` (although I guess there was no difference).

deleted get_equivalent_atoms 

---

CONTRIBUTING.rst

say what should be used instead

deprecation warning updated

---

pyiron/lammps/base.py
tests/lammps/test_base.py

Check if atoms are within box (along non-periodic sides)

Validate lammps run

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Problem addressed [here](https://github.com/pyiron/pyiron/issues/791)

error when repeat gets a float

---

pyiron/lammps/base.py
tests/lammps/test_base.py

Compatibility with [this](https://pyiron.github.io/source/faq.html)

time replaced by steps

---

pyiron/dft/job/generic.py
pyiron/sphinx/base.py
pyiron/sphinx/interactive.py
pyiron/vasp/base.py
tests/sphinx/test_base.py

Following [this discussion](https://github.com/pyiron/pyiron/issues/777) and last pyiron meeting.

number of electronic steps changed

---

pyiron/base/job/generic.py
pyiron/base/job/jobtype.py
pyiron/base/project/generic.py
pyiron/base/project/store.py
pyiron/gpaw/pyiron_ase.py
pyiron/interactive/scipy_minimizer.py
pyiron/interactive/sxextoptint.py
pyiron/project.py
tests/testing/test_exampleJob.py

Following [this discussion](https://github.com/pyiron/pyiron/issues/802)

Implement delete_existing_job in create_job

---

pyiron/atomistics/job/atomistic.py
pyiron/dft/job/generic.py
pyiron/gaussian/gaussian.py
pyiron/interactive/scipy_minimizer.py
pyiron/interactive/sxextoptint.py
pyiron/lammps/base.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py
pyiron/sphinx/base.py
pyiron/sphinx/interactive.py
pyiron/vasp/base.py
pyiron/vasp/interactive.py

In response to the [major update issue](https://github.com/pyiron/pyiron/issues/773), I started to look at the consistency between codes and the content on the website. Feel free to add more stuff.

Consistency of codes + website

---

pyiron/table/datamining.py

The type error from issue #835 should be fixed with this new function.
At least in my local hpc_ugent_2020 branch.

Numpy arrays were incompatible with JSON

---

pyiron/base/job/interactive.py

Change default from 1 to 10000

Update flush frequency

---

pyiron/base/job/jobtype.py

Bug introduced with https://github.com/pyiron/pyiron/pull/851

create_job deletes jobs 

---

pyiron/base/database/filetable.py
pyiron/base/database/jobtable.py

reset pandas display options w/o full_table

---

pyiron/atomistics/job/interactive.py
pyiron/atomistics/structure/atoms.py

I did this mainly because `get_structure()` was returning a non-periodic box

pyiron atoms changed to pbc when not specified

---

pyiron/base/master/generic.py

Raise an error when a finished job is appended to the GenericMaster

Fix GenericMaster append

---

pyiron/base/job/generic.py
pyiron/base/project/generic.py

check job objects rather than job id

Fix queue_check_job_is_waiting_or_running()

---

pyiron/base/server/queuestatus.py

do not iterate if the job is already finished

fix wait for job

---

pyiron/vasp/structure.py
pyiron/vasp/vasprun.py
tests/vasp/test_structure.py

Based on https://github.com/pyiron/pyiron/pull/858

VASP always return periodic cells

---

pyiron/sphinx/base.py

Explained [here](https://github.com/pyiron/pyiron/issues/891)

small bugfix

---

pyiron/base/master/flexible.py

@SanderBorgmans pointed this out in https://github.com/pyiron/pyiron/commit/1b1a7812ae0858f252f5c67ba3a5e333fc646292

Fix Bug in FlexibleMaster

---

pyiron/base/server/generic.py

convert server.run_time to int

---

pyiron/atomistics/job/structurecontainer.py

just small fixes in the docstring that should have been part of #873

fix docstrings

---

tests/lammps/test_base.py

Learning commit

---

pyiron/table/datamining.py

Reducing the memory foot print of the pyiron tables.

Accelerate pyiron table

---

pyiron/base/database/filetable.py
pyiron/base/project/generic.py
pyiron/base/settings/generic.py

Based on https://github.com/pyiron/pysqa/pull/37

Support multiple cluster

---

pyiron/vasp/base.py

Setting the convergence precision when calling these functions

Fix vasp calc

---

pyiron/vasp/base.py

Generalizing fixing the constraint!

Fixing spin_constraint

---

pyiron/vasp/base.py
tests/vasp/test_vasp.py

Also this function should not overwrite the existing electronic convergence.

:bug: in `calc_minimize`

---

notebooks/water_MD.ipynb

The water MD notebook only used the last structure of the MD. I add short computation of a radial distribution function averaging more snapshots

:memo: Update water MD tutorial

---

pyiron/atomistics/job/structurecontainer.py
pyiron/base/job/generic.py
tests/backwards/test_sphinx_load.py
tests/backwards/test_structure_container_load.py
tests/backwards/test_structure_container_save.py

@pmrv I reverted the pull request as they crashed the build system - I posted the error here https://github.com/pyiron/pyiron/pull/909 - as I was not sure about which part is broken I reverted both.

Struct back

---

pyiron/base/database/jobtable.py

Do not merge this one instead merge https://github.com/pyiron/pyiron_base/pull/8

project path fix

---

pyiron/__init__.py

https://github.com/pyiron/pyiron_base/pull/10

move jedi fix to pyiron_base

---

pyiron/project.py

importing didn't work when the directory contained other directories

changed copy raw files option in import from path to ignore directories

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

small bugfix (no consequence and probably no review required)

Apply strain bugfix

---

pyiron/lammps/base.py
tests/lammps/test_base.py

Use default potential

---

pyiron/atomistics/master/phonopy.py
tests/atomistics/master/test_phonopy.py

in the conversions between phonopy and pyiron magmoms were lost. I don't know if this is the best way to restore them

phonopy spins added

---

pyiron/atomistics/master/phonopy.py
pyiron/testing/randomatomistic.py
tests/atomistics/master/test_phonopy.py

change jobs names for child jobs in phonopy

---

README.rst

https://github.com/features/codespaces

With the introduction of Github codespaces we no longer need Gitpod

---

pyiron/sphinx/base.py

This is just renaming locked -> read-only as this exists in the base class since pyiron-base=0.18

Use read-only attribute of InputList

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Install dependencies via conda - still the unit tests do not work as I have to figure out how to configure visual studio code to include the repository in the python path.

Codespaces

---

pyiron/sphinx/base.py
pyiron/sphinx/interactive.py

```
pr = Project("test")
structure = pr.create_ase_bulk("Al", cubic=True)
job = pr.create_job(pr.job_type.Sphinx, "sphinx")
structure[0] = "Ca"
print(job.list_potentials())
job.potential.Al = "Al_sv_GW"
job.potential.Ca = "Ca_sv_GW"
job.run()
```

Implement S/PHI/nX potential setter

---

pyiron/interactive/sxextoptint.py
pyiron/sphinx/base.py
pyiron/sphinx/interactive.py
tests/sphinx/test_interactive.py

I guess no one used it and it was making the codes unnecessarily difficult to read

Coarse run

---

pyiron/__init__.py
pyiron/interactive/activation_relaxation_technique.py
tests/interactive/test_activation_relaxation_technique.py
tests/interactive/test_artint.py

activation relaxation technique added

---

pyiron/vasp/outcar.py

https://github.com/pyiron/pyiron/pull/1050

vasp/outcar : Remove white spaces

---

pyiron/atomistics/master/murnaghan.py

Writing structure to output with polynomial and EOS fits

---

pyiron/atomistics/job/atomistic.py
tests/atomistics/job/test_atomistic.py

Initially I just wanted to add periodic boundary conditions, but I ended up making the code a bit more compact and probably more efficient.

Get displacement

---

pyiron/__init__.py
pyiron/interactive/activation_relaxation_technique.py
tests/interactive/test_activation_relaxation_technique.py

Following today's meeting I changed `ARTInteractive` to `ART`.

Art name changed

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Since NGLView doesn't give coordinates or color map, I added plotly.

plotly added for structure plot

---

pyiron/project.py

Descriptions of docstrings for import_from_path and import_single_calculation methods.

Docstring for import_from_path method

---

pyiron/atomistics/structure/atoms.py
pyiron/thermodynamics/hessian.py
tests/atomistics/structure/test_atoms.py
tests/thermodynamics/test_hessianJob.py

Implement unit test for selective dynamics

---

pyiron/atomistics/structure/atoms.py

The `copy()` part was missing.

Fix plot3d

---

pyiron/lammps/control.py
tests/lammps/test_control.py

There was some debate over how to handle these lines over in [PR 1083](https://github.com/pyiron/pyiron/pull/1083), and I didn't want to wade in with a third opinion ;) But now that that's safely merged, here's my take on the logic for checking if a pressure is isotropic and hydrostatic.

Simplify logic

---

pyiron/atomistics/job/sqs.py

based on https://github.com/pyiron/pyiron_base/pull/61

fix sqs publication

---

pyiron/interactive/scipy_minimizer.py

I included a pressure tolerance attribute. Default set to 1 MPa. I guess it's low enough.

change pressure tolerance

---

pyiron/atomistics/job/atomistic.py

This just passes the parameter through to the NGL object.

Add camera option to animate_structure as in plot3d

---

pyiron/atomistics/job/interactive.py

I will not wait for 24h for this one.

spin setter removed if not implemented

---

pyiron/atomistics/structure/atoms.py

Since we started using get_extended_positions also independently of get_neighbors and I find it quite confusing that it not only returns the distances but also indices, I made indices an option.

add return_indices in get_extended_positions

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

This does essentially the same as `center_coordinates_in_unit_cell` but it instead returns positions.

get wrapped positions created

---

pyiron/interactive/scipy_minimizer.py

Reverts pyiron/pyiron#1095
Sorry I have to revert this one since the question remained unanswered.

Revert "SciPyMinimizer: Keep default values from self.input"

---

pyiron/atomistics/structure/atoms.py

Very minor touchups to the wonderful [switch from ovito to pyscal](https://github.com/pyiron/pyiron/pull/1192)

Pyscal consistency

---

pyiron/atomistics/structure/neighbors.py
tests/atomistics/structure/test_neighbors.py

Bugfix get neighbors

---

pyiron/__init__.py

I do not think the Atoms class belongs there.

Remove Atoms from JOB_CLASS_DICT

---

pyiron/atomistics/structure/factory.py

Dependent on [pyiron/pyiron_base#83](https://github.com/pyiron/pyiron_base/pull/83)

Inherit from PyironFactory

---

pyiron/lammps/interactive.py

interactive + langevin gives physics that depends on n_print.
Full discussion in #1173

Warn users about combining Lammps interactive and langevin 

---

notebooks/pipeline.ipynb

For now I just disable interactive mode

Fix the failing pipeline notebook

---

pyiron/sphinx/base.py
tests/sphinx/test_base.py

[URGENT] ekt unit corrected

---

pyiron/lammps/base.py

In case no log.lammps file is written and no dump.out files exists pyiron now only raises a warning but no longer crashes.

Enable user defined LAMMPS scripts

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Deleting tags properly when passing boolean arguments

Fix delete

---

pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/neighbors.py
tests/atomistics/structure/test_neighbors.py

Norm for the distance calculation can now be changed.

Neighbors norm order

---

pyiron/atomistics/master/parallel.py
pyiron/atomistics/master/serial.py

Fix https://github.com/pyiron/pyiron/issues/1267

Fix ParallelMaster

---

.ci_support/environment.yml
.github/workflows/unittests.yml
setup.py

I made a mistake and pushed this directly on master by accident.  I reverted it and then reverted the revert to create this PR, hope it didn't break anything in between.

Update to pyiron_base>=0.1.41 and use pip check in tests

---

pyiron/sphinx/base.py
tests/sphinx/test_base.py

Problem raised [here](https://github.com/pyiron/pyiron/issues/1262)

restore set_check_overlap

---

pyiron/lammps/base.py

to support multiple run commands

Extend lammps parser

---

.ci_support/environment.yml
pyiron/thermodynamics/interfacemethod.py

To include the voronoi fix https://github.com/srmnitc/pyscal/issues/95

Update Pyscal version 

---

pyiron/atomistics/structure/_visualize.py

Problem stated [here](https://github.com/pyiron/pyiron/issues/1281).
Closes #1281

prevent mirror when maximum value is negative

---

pyiron/__init__.py

```
from pyiron_base import Project
pr = Project(".")
print(dir(pr.job_type))
import pyiron
print(dir(pr.job_type))
```

Import all modules starting with pyiron_*

---

CONTRIBUTING.rst

As discussed in todays pyiron meeting

Add contribution guidelines

---

docs/source/installation.rst

Just a quick paragraph as we just discussed in the meeting.

Document module purge recommendation

---

.github/workflows/deploy.yml
CONTRIBUTING.rst

merging the changes made on the contribution guidelines (seen [here](https://github.com/pyiron/pyiron/pull/1410)

Update contribution guidelines

---

CONTRIBUTING.rst

changes from the already closed pull request #1415
@niklassiemer I hope now there are any things we have missed.

[ci skip] Update CONTRIBUTING.rst

---

.ci_support/environment.yml
setup.py

This should fix the numpy related issues

Update pyiron_atomistics 0.2.62

---

docs/index.rst

test whether website shows new installations or not

website appearance of new install instructions

---

docs/source/installation_quickstart.rst
docs/source/installation_remote.rst

fixes indenting for sphinx rendering on website

Fix_code_indenting_install

---

docs/source/installation_quickstart.rst

more minor fixes to prettify installation instructions

More_fixes_website

---

docs/source/installation_remote.rst

broken :code: formatting in docs

---

docs/source/installation.rst

install changes p1

---

docs/source/installation.rst

small fixes

---

docs/source/installation.rst

Revert "Remove duplicate install section"

---

docs/source/installation.rst

Revert "fix submenus properly"

---

docs/source/installation.rst

---
name: New Feature
about: Submit a pull request that adds new Features (complete files) to pyiron
title: ''
labels: enhancement
assignees: ''
---
**Summary**
**Related Issue(s)**
**Backward Compatibility**
**Implementation Notes**

Fix submenu

---

notebooks/test_pyiron_installation.ipynb

Revert "remove osx mention of GPAW"

---

docs/source/installation.rst

https://github.com/pyiron/pyiron_base/issues/1114 fixes this (hopefully)
https://github.com/pyiron/pyiron/pull/1495 and makes this one redundant - @niklassiemer

Fix queue.yaml example and refer to pysqa documentation.
