pyiron/base/job/generic.py
pyiron/lammps/base.py
pyiron/vasp/base.py

Restart files are not compressed, in addition only job types which have self._compress_by_default enabled compress their output files.

Compress all output files by default

---

pyiron/atomistics/job/atomistic.py

Now trajectories can be written to any output format by the ase writer with added features of selecting the atoms and the exact time steps for which we want the animation!

Write traj

---

pyiron/atomistics/job/atomistic.py
pyiron/lammps/base.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py

Adds the "zero yes" keyword argument to Lammps Langevin thermostat calls and renames some Lammps MD variables.
The key issue was that the Langevin thermostat adds random forces to the system, and without "zero yes" this can produce a net force on the centre of mass, causing drift over long simulations. Lammps already has the built-in keyword to prevent this. I'm not even making it optional because I don't see why you would ever want your CoM to drift!
I also renamed the `delta_temp` and `delta_press` variables to `temperature_damping` and `pressure_damping`, respectively. This is more in line with our "full name" naming scheme, and also (IMO) more intuitive since they have units of time and not units of $\Delta T$ or $\Delta P$. The original variable names are still usable but print a …

Langevin fix

---

pyiron/atomistics/job/interactivewrapper.py
pyiron/base/master/generic.py
pyiron/base/master/serial.py

If the number of cores for the child is larger than the number of cores for the master, set the number of cores for the master to the same level as the number of cores for the child.

Increase number of cores for the GenericMaster

---

pyiron/base/master/generic.py

`GenericMaster` requires an argument for pop. New patch has default behaviour that without an argument it tries to pop the -1th element.

Make behaviour the same as for other python objects that pop

---

pyiron/atomistics/structure/atoms.py

Modifications `plot3d` colouring capability.
- Colouring by the scalar field now lets the user define a colourmap (default is blue-red divergent) and limits for which scalars should be mapped to the extrema of the colourmap.
- An explicit per-atom list of colours can also be given (HTML names or hex codes (sort of...some colours come out wrong)). 
- The rest of the functionality (e.g. vector colouring, axes, etc.) should be the same, but I did make code modifications for streamlining and readability.
- Docstrings everywhere.

Plot3d colours

---

pyiron/atomistics/job/interactivewrapper.py

As discussed [here](https://gitlab.mpcdf.mpg.de/pyiron/pyiron-support/issues/137)

ref_job gives a warning if the job is not set to interactive

---

pyiron/atomistics/structure/atoms.py
pyiron/lammps/structure.py

It still requires to set the cutoff (job.cutoff_radius) and the bonds are not correctly identified by LAMMPS

trying to fix bond style

---

pyiron/vasp/base.py
tests/static/vasp_test_files/full_job_sample/INCAR
tests/vasp/test_vasp_import.py

This is necessary when importing calculations. For some reason the initial magnetic moments are not written in the OUTCAR file

Now parses magnetic moments from INCAR file

---

pyiron/lammps/interactive.py

calc_minimize convergence values changed and function doc stringed.

calc_minimize convergence values changed and function doc stringed.

---

pyiron/atomistics/job/interactive.py

Set previous structure to interactive job when run_if_interactive is executed.

fix for run_if_interactive 

---

pyiron/atomistics/master/phonopy.py
pyiron/base/generic/parameters.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py
pyiron/testing/randomatomistic.py
tests/base/generic/test_genericParameters.py
tests/lammps/test_lammps.py
tests/testing/test_exampleJob.py
tests/testing/test_exampleJob_non_modal.py

This allows input like:
```
job.input['fix___langevin'] = 'blabla'
```
as we as all the other input items which require more than one term.

lammps input corrected

---

pyiron/atomistics/job/atomistic.py
pyiron/atomistics/job/interactive.py
pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/phonopy.py
pyiron/vasp/interactive.py
pyiron/vasp/structure.py
pyiron/vasp/vasprun.py
tests/atomistics/structure/test_atoms.py
tests/vasp/test_vasprun.py

`scaled_positions` had to be abolished for the following reasons:
1. It is not that commonly used
2. It is not possible to keep `positions` and `scaled_positions` synchronised, since when we try to change an element, e.g. via `positions[0,0] = 0.5`, the setter is not called and therefore we have no control over `scaled_positions`.
3. We would like to keep the functionality of `positions` as a numpy array.
Therefore, please use `set_scaled_positions` and `get_scaled_positions` in the future.

Set relative

---

pyiron/vasp/base.py
tests/vasp/test_vasp.py

Added ways, how to deal with EDDRMM error in VASP. Three ways are possible:
- ignore: Just ignore error.
- not_converged: set status to 'not_converged' (default).
- restart: set status to 'not_converged' and restarts the job with ALGO = 'Normal' and eddrmm = 'not_converged' from initial structure.

Eddrmm handling

---

pyiron/lammps/control.py

Otherwise the Lammps 2017 crashes.

lammps compatible to old versions

---

pyiron/interactive/sxextoptint.py

For the symmetry calculation of SxExtOpt, initial magnetic moments are also taken into account with this update. This update will not affect the behaviour for the old version (i.e. if an old version of SxExtOpt is used, the symmetry is calculated without taking magnetic moments into account).

Sxextopt considers magnetism

---

pyiron/interactive/sxextoptint.py

Added explanations to the input parameters.
Magnetic moments are rounded for the ID's because otherwise SxExtOpt things there are a lot of different atom types.

Sxextopt str

---

pyiron/base/database/jobtable.py
pyiron/base/project/generic.py
pyiron/base/server/queuestatus.py

`pr.job_table(full_table=True)` will show the entire table, regardless of the number of jobs. The same applies to `queue_table()` and `queue_table_global()`. For `job_table`, there could be a conflict with `max_colwidth` (which I don't think is a problem).

full_table now allows users to see the entire pandas queue table

---

pyiron/base/generic/parameters.py

To ensure the `GenericParameters` avoids storing `numpy` arrays in the HDF5 file

bugfix in set_value: (Felix's commit)

---

pyiron/lammps/base.py
pyiron/lammps/control.py
pyiron/lammps/interactive.py
pyiron/lammps/structure.py
tests/lammps/test_base.py
tests/lammps/test_interactive.py

Key features:
- Convert to and from triclinic cells for Lammps
- Allow non-diagonal pressures (i.e. Pxy, Pxz, and Pyz) during Lammps relaxation and minimization
- Fun extra: synchronized `calc_minimize` docstrings to a single place then linked it in other places (plus tests to make sure the defaults stay validly described)
I had originally intended just to get triclinic cells working, e.g. for running primitive cells (there was a conversion in place but it had a bug), but wound up implementing a more complete binding to cell shape changes.

Lammps triclinic repairs and extension

---

pyiron/vasp/base.py
pyiron/vasp/potential.py
tests/static/vasp/potentials/potpaw_PBE/Fe/POTCAR
tests/vasp/test_potential.py

The [VASP wiki](https://www.vasp.at/wiki/index.php/ENCUT) states 
> For consistency reasons we still recommend to specify the cutoff manually in the INCAR file and keep it constant throughout a set of calculations.
e.g. if you're looking at the segregation of various solutes to a particular defect, then you should use the highest ENCUT among host and all solutes across all calculations, even that of your pure-host defect. 
Thus, it's nice to be able to quickly assess what that cutoff value is for a given set of elements.

Enmax finder

---

pyiron/sphinx/base.py

SPHInX can now be relaunched when a simulation does not converge within the allocated computation time (e.g. 4 days). It had already been possible to create a restart job by `job.restart()`, but it did not reflect the final results automatically (i.e. the output files of the not converged simulation were not parsed). With this fix, a single  `job.restart()` will parse the output files of the not-converged simulation **and** it sets the status to `not_converged` (instead of `aborted` which had been the case before).

sphinx restart 

---

pyiron/base/project/generic.py

enable in Project().remove() now has to be explicitly set to True in order for the project to be deleted. I'm doing this because I sometimes write `remove()` instead of `remove_job()`, where I write a job name, which enacted `remove()` because `if job_name` was True.

enable in Project().remove() has to be set explicitly to True

---

pyiron/atomistics/structure/atoms.py

This version adds a new kwarg 'pretty_translation' ahead of the kwarg 'eps'. We ran
into trouble by passing kwargs by order.
All this does is be more explicit with the kwargs, so I will just merge it directly.

Make wrap compatible with ase version 3.19.0

---

pyiron/atomistics/job/interactive.py
pyiron/sphinx/interactive.py
tests/sphinx/test_interactive.py

Now the input has essentially the same structure. This has two important implications:
1. It can be made faster (up to 4 times, combined with the output stuff)
2. If the input is not defined (e.g. cell in DFT), it can be removed beforehand, which allows for a more secure input handling.
I add a notebook that I used for testing:
[interactive_speedup.ipynb.txt](https://github.com/pyiron/pyiron/files/4026409/interactive_speedup.ipynb.txt)

Interactive input speedup

---

azure-pipelines.yml

Drop Python 2.7 tests in favour of Python 3.8 

---

pyiron/base/job/generic.py
pyiron/base/master/serial.py

Enforce run_mode modal when submitting to the queue - it is important that the master process never stops, otherwise the queuing system is going to kill the job. At least modern queuing systems like Slurm do. @sudarsan-surendralal this should fix your issue with the SerialMaster.

Fix for SerialMaster

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Two issues are fixed in this pull request based on this issue https://github.com/pyiron/pyiron/issues/542
- The correct implementation of the slice for the `__setitem__()` for the `Atoms` class
- Fixing a bug with the assignment of atoms and updating the `species` and `indices` that was broken by the example in the issue above

Fix _setitem__

---

pyiron/gaussian/gaussian.py

Except ImportErrors for packages not in dependencies
I am a bit confused why the tests did not fail but when we do not have the package included the import should fail.

Fix Gaussian

---

pyiron/interactive/sxextoptint.py

The last version worked only if SxExtOpt was used as a stand-alone wrapper. Fortunately, it was also located in a wrong place (inside `__del__`) and therefore is unlikely to disturb current jobs, but this pull request corrects the error.

location had to be indicated

---

.ci_support/azure-unix-test-template.yml
.ci_support/setup_pyiron.sh
appveyor.yml
pyiron/atomistics/structure/atoms.py
pyiron/dft/job/generic.py
pyiron/sphinx/base.py
pyiron/vasp/base.py
pyiron/vasp/vasp.py
setup.py
tests/sphinx/test_base.py

Using the tool [seekpath](https://github.com/giovannipizzi/seekpath), high symmetry points and paths are created automatically.
The paths are now stored as list of tuples including start and end points, thus discontinuous paths are possible to calculate. E.g. `[("G", "H"), ("H", "N"), ("G", "P")]`.

Rewrite line mode for band structure calculations

---

pyiron/sphinx/base.py
tests/sphinx/test_base.py
tests/sphinx/test_interactive.py

When the VASP potentials are available, they are used by default, to switch to the JTH potentials use: `job.input["VaspPot"] = False`
If the VASP potentials are not available, this option is false by default.

Spx potential - some more fixes 

---

pyiron/sphinx/base.py

I wanted to have the number of valence electrons to analyse the number of empty bands.

parse the number of valence electrons

---

pyiron/vasp/base.py

Just cleaning up a little bit. Since both functions `restart_from_wave_and_charge` and `restart_from_charge_density` used different code to get the correct `ICHARG` tag, I wrote a private function `_get_icharg_value` used for both.

Rewrite restart_from_... functions

---

pyiron/base/generic/hdfio.py
pyiron/base/job/jobtype.py
tests/atomistics/structure/test_atoms.py

The code is still very much focused on the Atoms object but in general the idea is to allow any object to be reloaded from the HDF5 file, with the `to_object()` function:
```
from pyiron.base.generic.hdfio import ProjectHDFio
pr = Project('test')
structure = pr.create_structure('Fe', 'bcc', 2.78)
hdf5_file = ProjectHDFio(project=pr, file_name='store.h5')
structure.to_hdf(hdf5_file)
hdf5_file['structure'].to_object()
```
Previously this was only possible for pyiron jobs.

Reload atoms from HDF5 file

---

pyiron/sphinx/interactive.py

This was needed since `interactive_close` is not called when the job does not finish within the cluster time, in order to transfer tags inside `output/interactive` to `output/generic`

Spx interactive parser

---

pyiron/base/job/jobstatus.py

When (accidentally) trying to access a job status check that is not actually defined, like `job.status.queued` instead of `job.status.submitted` you'd get a weird error message like this
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-ac32335f0f7e> in <module>
----> 1 jre.status.foo
~/software/pyiron/pyiron/base/job/jobstatus.py in __getattr__(self, name)
243             return self._status_dict[name]
244         else:
--> 245             super(JobStatus, self).__getattr__(name)
246 
247     def __setattr__(self, name, value):
AttributeError: 'super' object has no attribute '__getattr__'
```
which doesn't explain the actual issue (that you typed the wrong name). …

fix exception on accessing missing attribute on JobStatus

---

pyiron/sphinx/base.py
tests/sphinx/test_base.py

According to [sxrepo](https://sxrepo.mpie.de), `ricQN` is faster than `linQN` as a minimisation scheme. As far as I know `linQN` was there only for historical reasons so I don't think there's someone who strongly opposes the idea of switching it to `ricQN`.

calc_minimize changed to ricQN

---

pyiron/atomistics/structure/generator.py
tests/atomistics/structure/test_atoms.py

I like how easy it is to build simple surfaces using a string like "fcc111", but as far as I can tell, there is no way to use `pyiron.atomistics.structure.generator.create_surface` to make a slab whose miller indices aren't hard-coded into pyiron. I noticed that `create_surface` accepts "ase_surf" as a surface type, but that doesn't seem to work since ase_surf takes fundamentally different args than e.g. fcc111.
The new function `create_hkl_surface` basically wraps ase.build.surface, so it can handle a more flexible set of args, including arbitrary miller indices.
```python
from pyiron.atomistics.structure.generator import create_hkl_surface, create_structure
s1 = create_hkl_surface("Al", [10, 8, 7], layers=20, vacuum=10)
Mo_bulk = create_structure("Mo", "bcc", 3.0)
s2 = …
```

new create_hkl_surface function

---

pyiron/vasp/base.py

Ensuring vasp runs only 1 ionic step for static calculations

Making sure vasp runs only 1 ionic step for a static calculation

---

pyiron/lammps/control.py
tests/lammps/test_base.py

Pointed out [here](https://github.com/pyiron/pyiron/issues/655)

calc_md with pressure 0 corrected

---

pyiron/dft/job/generic.py
pyiron/vasp/base.py
pyiron/vasp/interactive.py

If you use `ham.get_structure(iteration_step)`, the spin tag will be updated. Also a function `get_magnetic_moments()` is created, but for now it is located at `dft/job/generic.py`.

Update spin tag in structure

---

pyiron/sphinx/base.py

A simple job: 
```
pr = Project('bulk_dft')
job = pr.create_job(pr.job_type.Sphinx, 'job_dft')
job.structure = pr.create_ase_bulk('Al')
job.run()
```
Should not raise a warning, because that might confuse beginners.

Remove warning for default jobs

---

pyiron/atomistics/structure/atoms.py

Otherwise filters defined by the user are overwritten

Remove warnings filter

---

pyiron/vasp/base.py

The `set_kpoints()` function is defined once in the generic job class:
https://github.com/pyiron/pyiron/blob/master/pyiron/dft/job/generic.py#L191

VASP: Remove redundant set_kopints() function

---

pyiron/interactive/sxextoptint.py

This should fix the following errors in the automated tests: 
```
Exception ignored in: <function SxExtOpt.__del__ at 0x7f8b47b11440>
2596Traceback (most recent call last):
2597  File "/home/travis/build/pyiron/pyiron/pyiron/interactive/sxextoptint.py", line 276, in __del__
2598    self.interactive_close()
2599  File "/home/travis/build/pyiron/pyiron/pyiron/interactive/sxextoptint.py", line 196, in interactive_close
2600    os.remove(posixpath.join(self.working_directory, "control"))
2601FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/pyiron/pyiron/SPX_CHECK_ALL/sxextopt_Al_hdf5/sxextopt_Al/control'
```

Fix deletion of named pipes

---

pyiron/base/database/jobtable.py
pyiron/base/server/queuestatus.py

pyiron shouldn't reset pandas options that the user might have set externally as that can be confusing.  I think ideally it also wouldn't set them, but `full_table` is just too useful.  I'm also ok with keeping the current behavior, because I see the convenience, but I just tripped over this and thought somebody else might too.  Anybody has hard opinions on this?

don't reset pandas options

---

notebooks/tests_sphinx_sphinx_check_all.ipynb

Sphinx tests

---

pyiron/atomistics/job/atomistic.py

After having had to write `np.linalg.norm(job.output.forces, axis=-1).max(axis=-1)` so many times in order to check force convergence, I finally implemented the output property. User just has to put `job.output.f_max` -> I'm not really sure if this is a good name (although it's essentially equivalent to LAMMPS notation). Let me know what you think.
And maybe we should put in pyiron documentation that force convergence is the maximum force magnitude for structure optimisations (if it's not already written).

maximum forces for the output added

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Points are repeated in the same way as `repeat`, e.g.:
```
structure.repeat_points(points=[0.1, 0.2, 0.3], rep=[3, 3, 3])
```
The return value is the set of points repeated in each direction.
Tests and DocString will be added shortly.

repeat_points added

---

pyiron/sphinx/base.py

Fixes #775; parser looks for lines starting with "| Z=" instead of just "| Z"

:bug: Fix valence parser for elements starting with 'Z'

---

tests/sphinx/test_base.py

`sphinx` in `test_base.py` is supposed to be for the latest version and not specifically for `2.6.1`.

sphinx version removed

---

pyiron/base/project/generic.py

My common mistake:
```
pr.remove_jobs(job_name)
```
which is then understood by pyiron as:
```
pr.remove_jobs(recursive=True)
```
while what I want is:
```
pr.remove_job(job_name)
```

safer behaviour for remove_jobs

---

CODE_OF_CONDUCT.md

Based on https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

Adding a code of conduct 

---

pyiron/base/master/parallel.py

```
pr = Project("murn")
structure = pr.create_ase_bulk("Al", cubic=True)
job = pr.create_job(pr.job_type.Lammps, "lmp")
job.structure = structure
job.potential = 'Al_Mg_Mendelev_eam'
job.server.run_mode.interactive = True
murn = job.create_job(pr.job_type.Murnaghan, "murn")
murn.server.run_mode.non_modal = True
murn.run()
pr.wait_for_job(murn)
```

Execute interactive master jobs in the background

---

pyiron/lammps/base.py
tests/lammps/test_base.py

When setting a custom potential on lammps jobs via pandas dataframe, we used to accept everything.  This checks at least whether the potential advertises the correct species list for the species present in the structure.  I could also add checks for the other members as per [FAQ](https://pyiron.readthedocs.io/en/latest/source/faq.html#how-to-use-a-custom-potential-in-lammps), but I'm not 100% sure what all of them are or what downstream code expects there.

check if potential supports correct elements

---

pyiron/base/generic/inputlist.py

sphinx doesn't recognize code listings with `>>>` unless they are on their own paragraph

fix example formatting in InputList

---

pyiron/base/job/generic.py

pysqa returns None now if it encounters a submission error instead of
raising an Exception
See discusion in #899.

check for None after submit_job

---

pyiron/vasp/base.py
pyiron/vasp/potential.py

Use:
```
job.potential["Al"] = "Al_sv_GW"
job.potential["Ca"] = "Ca_sv_GW"
```
Or:
```
job.potential.Al = "Al_sv_GW"
job.potential.Ca = "Ca_sv_GW"
```
In addition you can list the available potentials with:
```
job.list_potentials()
```
Or get more detailed information with:
```
job.potential_view
```
Finally to change the pseudo potential use:
```
job.input.potcar["xc"] = "LDA"   # "GGA" or "LDA"
```
To mix different pseudo potential functionals you need to specify the absolute path to the corresponding potentials. Anyway mixing different pseudo potential functionals is not recommended.

Simplify setting potentials for VASP

---

pyiron/atomistics/job/structurecontainer.py
pyiron/base/job/generic.py
tests/backwards/test_sphinx_load.py
tests/backwards/test_structure_container_load.py
tests/backwards/test_structure_container_save.py

The serialization format for `StructureContainer` changed due to #873 and I didn't catch that.  This bumps the HDF version for that job and adds a compatible `from_hdf`.

Backwards compatible loading for StructureContainer & tests

---

docs/source/hdf5.rst
pyiron/base/generic/hdfio.py
pyiron/base/job/generic.py
pyiron/base/master/generic.py

It turns out there's only small changes `to_object()` needed to allow loading any type of object from HDF5. I'll add tests & more docs, but I also wrote up a bit about how writing and reading works [here](https://github.com/pyiron/pyiron/blob/jobcore/docs/source/hdf5.rst) and I'd like your comments for the meeting tomorrow.  Naturally it's not quite complete and I'm not sure the page should mesh with the rest of the docs, but it's a start.

allow abitrary object loading with `to_object()`

---

pyiron/vasp/base.py
pyiron/vasp/potential.py
tests/vasp/test_potential.py

Update the ability to pull ENMAX based on a bunch of atomic species to pull it based on a bunch of pseudopotential names, ala [pull request 908](https://github.com/pyiron/pyiron/pull/908).
e.g.
```
from pyiron.vasp.potential import get_enmax_among_potentials
get_enmax_among_species(['Mg', 'Al_sv_GW', 'Ca_pv'], return_list=True)
> (411.109, [200.0, 411.109, 119.559])
```

Vasp potential peeking

---

pyiron/lammps/base.py
pyiron/lammps/control.py

Without it `lammps.base.calc_vcsgc` fails for isobaric calculations because the pressure value isn't iterable.

Use rotation matrix in vcsgc too

---

pyiron/atomistics/master/parallel.py
pyiron/base/job/generic.py
pyiron/project.py

There was a small bug in the pipeline restart functionality + it was not possible to run more than one pipeline in the project due to the non-unique name of the master job. This is fixed now by adding the template job name as a prefix.

Pipeline restart fix + non-generic master job name

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

I was iterating over a `np.arange` for size convergence and ran into this. I've run into it before under the same circumstances, but I finally got tired enough of converting from `np.int64` to `int` to do something about it 😝

Int64 is int too

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

Discussed in [this issue](https://github.com/pyiron/pyiron/issues/951). The warning is not raised if the cell is periodic with no volume and `append` is used.
Closes #951

Append atoms

---

pyiron/dft/job/generic.py

kpoints per reciprocal angstrom threw an error if the resulting kpoint mesh was 0 for an axis. I am not sure about the reason for this behavior, but for me it made more sense to set it to 1 kpoint in this case. If there was some special reason for throwing an error I think it would be good idea to make that behavior optional.
Also corrected the function documentation to be consistent with the actual function.

Changed kpoints per reciprocal angstrom

---

pyiron/thermodynamics/hessian.py
tests/thermodynamics/test_hessianJob.py

Following @jan-janssen 's comment, replace the core part of `EinstenExampleJob` by `HessianJob`

flexible formats for force constants in HessianJob

---

tests/atomistics/master/test_murnaghan.py

With `AtomisticExampleJob`, volume convergence couldn't be seen, but this one will allow for testing convergence algorithm. 
In addition, the coverage will probably go above 60% with this pull request.

test murnaghan convergence

---

pyiron/atomistics/structure/atoms.py
pyiron/lammps/structure.py
tests/atomistics/structure/test_atoms.py

In the unit test I already included a Paradebeispiel (perfect example) for what `neigh.get_global_shells()` is useful for - For example, when a system is a perfect crystal with let's say one solute atom, the shell index 1 (and any other index) is not the same everywhere when we use `neigh.shells`. With `neigh.get_global_shells()`, you can be sure that wherever the same index can be found, the distance value is the same.

Get global shells

---

.ci_support/environment.yml
.ci_support/travis_setup_notebooks.sh
binder/postBuild
setup.py

By switching to pyiron_base 0.1.19 it is no longer necessary to create a `.pyiron` file as the pyiron resources are also installed via conda.

pyiron_base 0.1.19

---

pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/neighbors.py
tests/atomistics/structure/test_atoms.py
tests/atomistics/structure/test_neighbors.py

Summary:
- Distinction between global shells (based on all distances) and local shells (based on the distances of each atom) and `shells` now calls `get_local_shells` internally.
- `get_shell_matrix` now returns a list of sparse matrices (which hopefully will solve the memory issues Qais and I were encountering)
- `update_vectors` will update `vecs` and `distances` for the same indices without having to execute `get_neighbors` again. This works only if the largest distance is smaller than half the length in any direction (I'll explain why at the pyiron meeting)
- clustering methods we studied some time ago are now included in the class. They can be called as a child function from `get_local_shells` or `get_global_shells` or they can be called separately by `cluster_by_xxx` (the latter …

Extend get neighbors

---

pyiron/atomistics/structure/neighbors.py
tests/atomistics/structure/test_atoms.py
tests/atomistics/structure/test_neighbors.py

`find_neighbors_by_vector` now correctly identifies the atoms themselves if the given vector is very small.

Find neighbors

---

pyiron/vasp/base.py
pyiron/vasp/outcar.py

This parses the total elastic constants calculated to the hdf if they were calculated using IBRION= 6 . Maybe it would be interesting to divide between clamped elastic constants and ionic contributions but I don't know how to do that in a nice style.

Vasp parse elastic constants

---

pyiron/sphinx/interactive.py
pyiron/vasp/interactive.py

I got a few SPHInX simulations which didn't converge within the run time limit. Then I realized that the general flush frequency was raised to 10,000 before (did I do it?) and all information stored in `interactive_cache` was lost. Now the default is set to 1 inside SPHInX.
@sudarsan-surendralal : I'm sure that the same thing should be done in VASP

lowered flush frequency

---

pyiron/atomistics/job/interactivewrapper.py

This fixes an issue when trying to run a gpaw job in interactive mode, that occurs because the pyiron atoms object is converted to an ASE atoms object at some point. This feels like an ugly workaround and there is probably a better fix for this so any suggestions are very welcome.

Attempt to fix issue related to using ASE atom

---

pyiron/atomistics/structure/ovito.py

We want to extend the interface method https://github.com/pyiron/pyiron_meltingpoint to diamond crystals and for this we need a detector which is able to support diamond crystal structures, which is not the case for the common neighbour analysis.

Add analyse_ovito_diamond()

---

pyiron/lammps/control.py
tests/lammps/test_base.py
tests/lammps/test_control.py
tests/lammps/test_interactive.py

As discussed in bug #1074, a LAMMPS job converted the `pressure` input to a numpy array of type float, thereby converting `None` values to NaN, which was not checked correctly by later parts of the code.
Furthermore, hydrostatic pressures were handled incorrectly, by converting a scalar pressure p to a stress tensor [p,p,p,p,p,p] instead of [p,p,p,0,0,0] or [p,p,p,None,None,None] in some circumstances.
To be discussed: I believe that hydrostatic pressures can be applied correctly in all cases (even with rotation) by using [p,p,p,None,None,None], i.e., keeping the shear components fixed. I am not 100% sure it works when rotating the box, so if there is no consensus I would propose to disallow even hydrostatic pressure when the box has to be rotated and require a full stress tensor. The …

Fix LAMMPS pressure

---

pyiron/table/datamining.py
tests/table/test_datamining.py

```
2020-10-31 17:06:52,548 - pyiron_log - WARNING - The job table is being loaded instead of running. To re-run use the argument 'delete_existing_job=True in create_job'
```

pyiron table: Remove the annoying warning

---

pyiron/atomistics/job/interactive.py

Closes #1145 
The problem was related to the old implementation (I guess) where we distinguished between relative scale and absolute scale. Now since we have only the absolute system, the real positions should be checked instead of relative positions.

scaled positions changed to positions

---

notebooks/bandstructure.ipynb
notebooks/first_steps.ipynb
notebooks/hcp_workfunction.ipynb
notebooks/phonopy_example.ipynb
notebooks/structures.ipynb
notebooks/water_MD.ipynb

Replaced `from pyiron.project import Project` with `from pyiron import Project` in tutorials notebooks to be consistent with pyiron.org snippet

[ci skip] Update old syntax of importing Project in tutorials notebooks

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

The current implementation of `get_neighbors_by_distance` would fail in cases where the volume per atom of the supercell is large. For example
```
import numpy as np
pr = Project(".")
dx = 0.7
r_O = [0, 0, 0]
r_H1 = [dx, dx, 0]
r_H2 = [-dx, dx, 0]
unit_cell = 10 * np.eye(3)
water = pr.create_atoms(elements=['H', 'H', 'O'],
positions=[r_H1, r_H2, r_O],
cell=unit_cell, pbc=True)
water.get_neighbors_by_distance(1.3)
```
I've just made a simple fix so that at least 1 neighbor is counted.

Fix neighbors

---

pyiron/atomistics/structure/atoms.py
tests/atomistics/structure/test_atoms.py

The check for the warning previously failed if there aren't any neighbors to return

Debug no neigh

---

pyiron/sphinx/base.py

Add new line in `spins.in` which bash currently thinks doesn't end, which (in my personal case) is causing parsing problems.

[minor] add new line in spins.in

---

pyiron/atomistics/master/phonopy.py
tests/atomistics/master/test_phonopy.py

If you pass a `calc_md` or `calc_minimize` job as a phonopy reference, phonopy will run but will silently return crazy results (at least for minimize, not 100% sure for md). Let's stop that by validating the input.
I draft the solution here, but don't have time to test it and bring it all the way home. I think this is an excellent topic for one of our junior developers to take over and finish this PR!
[Linked issue](https://github.com/pyiron/pyiron/issues/1195).

Add check that reference job is static

---

pyiron/__init__.py
pyiron/atomistics/structure/atoms.py
pyiron/atomistics/structure/factory.py
pyiron/atomistics/structure/generator.py
pyiron/lammps/control.py
pyiron/project.py
tests/atomistics/structure/test_atoms.py
tests/atomistics/volumetric/test_volumetric_data.py

The atomistic `Project` class already has a lot of methods for creating structures, and I can see that we will only have more coming. For instance, I want easy access to `ase.io.read`.
So here I package these methods up in a new class, and add that class as an attribute of `Project`. I.e. `project.create_ase_bulk('Al')` --> `project.structure.create_ase_bulk('Al')`. This is a bit more typing, but in cleans up and organizes our tab completion, and the class structure will help as we extend the ability for generating structures (e.g. making grain boundaries, dislocations, etc.)
What is *not* done here:
- New, nicely structured tests for the `StructureGenerator` class.
- Very many new extensions (only binding ASE's read).
What I most want feedback on is really serious thought as to what we …

Spinoff structures

---

docs/source/installation.rst

I wanted to see what kind of DB is behind pyiron and went to the documentation of pyiron.
I've realised that it uses PostgreSQL (but with a typo: _PostgeSQL)._
Interestingly, google returns ~200,000 results for _PostgeSQL!_

[ci skip] Fix a typo: PostgeSQL-->PostgreSQL in installation.rst

---

pyiron/lammps/potential.py

This is a bug fix to the potential_available property based on the recent changes to the potential database https://github.com/pyiron/pyiron/pull/1179 
This is not an implementation of the newly discussed `set_to` feature. 
Assign potentials using autocompletion: 
```
job.potential = job.potential_available.pot_2018__Jeong_G_U__Pd_Al__LAMMPS__ipr1
job.potential = '2018--Jeong-G-U--Pd-Al--LAMMPS--ipr1'
```
Both lines are equivalent - we have to add a string in front of the potential names, as some potential names start with a number and we have to replace `-` with `_`.

Fix potentials available

---

pyiron/lammps/control.py
tests/lammps/test_control.py

A new lammps control interface to access [`fix move`](https://lammps.sandia.gov/doc/fix_move.html).
Currently tucked away hidden in `lammps.input.control` with no direct job access as it's probably just for experts/not something you can (currently) do in other codes(?).

Interface to lammps move

---

pyiron/atomistics/job/interactivewrapper.py
pyiron/atomistics/structure/atoms.py
pyiron/lammps/base.py
pyiron/vasp/potential.py

As anticipated there are a lot of instances where we only deprecate some arguments to a function, I will handle this in the next iteration of the decorator in pyiron_base and then update here.
There also some cases that I don't know how to handle, like this
https://github.com/pyiron/pyiron/blob/d410e585babd3b07326853de38134bd182b528bd/pyiron/lammps/interactive.py#L113
It'd be nice to also have them be handled by the `Deprecator`, to keep the messages uniform.  I'm thinking to expose a method there that just logs the warning and this method would be called in the decorator, but it would also be available manually.  If you have opinions on this, let me know.

Use new deprecate decorator

---

pyiron/lammps/control.py

remove one redundant self.modify and forbid changing thermo value directly. I'm not really sure if it was okay to delete `thermo=value`, but since we are defining `thermotime` I guess we shouldn't change `thermo` directly.

Remove redundant lines in LAMMPS input control

---

pyiron/atomistics/job/atomistic.py
pyiron/atomistics/job/interactive.py
pyiron/testing/randomatomistic.py

I wanted to make sure that also for interactive jobs the tags are copied. But then I realised that the `get_structure` in `atomistic.py` has little utility, and moreover in the interactive jobs the structure is copied at each step, which significantly reduces the efficiency. So I removed `get_structure` from `atomistic.py` (which makes you use only the one defined in `GenericAtomisticJob`) and introduced `_update_previous_structure`, which only updates the information and does not copy an entire structure.

update structure setter for interactive jobs

---

.ci_support/environment.yml

We do not need `pyqt` so using `matplotlib-base` should be faster: 
https://conda-forge.org/docs/maintainer/knowledge_base.html#matplotlib

Use matplotlib-base rather than matplotlib in conda environment

---

.ci_support/pypi_vs_conda_names.json
.ci_support/update_environment.py
.github/workflows/UpdateDependabotPR.yml

Update workflow for dependabot PRs

---

README.rst

As we discussed yesterday, we were missing some links to the detailed docs of atomistics and base.

Add backlinks to pyiron_{base,atomistics}

---

binder/postBuild

The lines for building nglview with jupyter are now deleted, as recommended by @muh-hassani in issue #1417.

Update postBuild - for pyiron in binder

---

notebooks/test_pyiron_installation.ipynb

Removes mention of OSX support for GPAW. Liam's issue here #1066 is fixed.

remove osx mention of GPAW

---

setup.py

Synchronizes the pypi representation of pyiron with the hard limit of python >3.8 expressed on [the conda forge feedstock](https://github.com/conda-forge/pyiron-feedstock/blob/c954babdba3bcd313738db2feeae0de6412a9123/recipe/meta.yaml#L24)

Remove pypi support for python versions not allowed by conda

---

docs/source/installation_hpc_config.rst

Small changes in the syntax for multiple hpc configs.

Correct syntax error in documentation for configuring multiple HPC clusters.

---

docs/index.rst

Following [@aageo25's request](https://github.com/pyiron/FAQs/issues/57) I added `Workshops` right below `Examples`.

Add workshop on the doc page
